import "./globals.css";
import { Poppins } from 'next/font/google'; // Import Poppins font
import Navbar from './Navbar'; // Import Navbar

// Konfigurasi font Poppins dengan subset Latin dan display swap
const poppinsRegular = Poppins({
  weight: '400', // Bobot regular
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppinsRegular.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
